[env:esp32-c3-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

; ESP-IDF 설정
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
board_build.flash_mode = dio
board_build.flash_size = 2MB

; 시리얼 모니터 설정
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; 업로드 설정
upload_speed = 115200
upload_port = /dev/cu.usbmodem1101

; ESP-IDF 컴포넌트 옵션
board_build.esp-idf.sdkconfig_path = sdkconfig.defaults

build_flags = 
    -DCONFIG_I2C_MASTER_FREQUENCY=100000
    -DCONFIG_SHT45_I2C_ADDR=0x44



